language: java
os: linux
dist: bionic

sudo: required

# specify to use docker
services:
  - docker

# specify the jdk to use
jdk:
 - openjdk17

env:
  global:
    - IMAGE_NAME=maskerwebservices
    - IMAGE_TAG=1.1.8
    # Following values set in Travis-ci setting so can eaily be changed.
    # IBM_CLOUD_REGION
    # REGISTRY_REGION
    # REGISTRY_NAMESPACE
    # IBM_CLOUD_API_KEY

# safelist - only work with these github branches
# will not take an env value for branch only string. 
branches:
   only:
   - travis-ci

# Added the following lines to see if would fix issue with ssl certificates, but moving to 
# linux dist bionic fixed the issue.
install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates -y
  - sudo update-ca-certificates
 
# Test install of new IBM Cloud CLI install script
#before_script:
#   - build_scripts/ibm_cloud_cli_tools_install.sh
 
# Build scripts
script:
  # Build code in Masker directory
  - echo $HOME
  - echo $(pwd)
  - cd Masker
  - mvn clean install -Dgpg.skip -q
  - ls target/*.jar
  # Build code in MaskWebServices directory
  - cd ../MaskWebServices
  - mvn clean install -Dgpg.skip -q
  - ls target/*.jar
  - ls target/*.war
  - cd ..
  # Build Docker image from Dockerfile
  #- if [[ -f Masker/target/Masker-1.1.4-jar-with-dependencies.jar ]] && [[ -f MaskWebServices/target/MaskWebServices-1.1.4.war ]]; then build_scripts/build_docker_images.sh ; fi
  - build_scripts/build_docker_images.sh
  - docker images

# unit test built image
after_success:
  - build_scripts/unit_test_image.sh
  - unit_test_result=$(cat unit_test_results) ; echo $unit_test_result
  - if [[ -f unit_test_results ]] && [[ $unit_test_result != "Passed" ]]; then echo "Here" ; fi

# before deploy login to ibm cloud & cloud image repo
before_deploy:
  - build_scripts/ibm_cloud_repo.sh

# deploy docker image into ibm's cloud image repo
deploy:
  provider: script
  skip_cleanup: true
  script: build_scripts/deploy_image_to_ibm_repo.sh
  on:
    branch: travis-ci

after_script:
  - docker images
  - ibmcloud cr image-list
